167 set admin role
Botomir/Botomir pull request #185
Opened 2021-05-12 22:46 UTC by FilipHasson

Closes: #167 
Fixes:
Related: 

---

**Describe the pull request:**

The bot should now be able to change which role is treated as the botomir-admin role if server admins wish to change it
---

Checklist:

- [x] Run `npm run lint` and ensure linter passes
- [x] Run `npm run test` and ensure tests pass
- [x] Verify that the changes work as expected on Discord
- [ ] Update documentation / not applicable
- [ ] Update changelog / not applicable

2021-05-12 22:54 UTC, SoorajModi commented on test/bot/commands/admin/setBotomirAdminRole.tests.js
> +describe('test setBotomirAdminRole', () => {
Bless ur soul for adding tests

2021-05-12 22:54 UTC, SoorajModi approved these changes

2021-05-12 22:56 UTC, SoorajModi commented
Also check off the last two points in the PR template, even if its n/a

2021-05-12 23:38 UTC, MarshallAsch requested changes

2021-05-12 23:38 UTC, MarshallAsch commented on bot/commands/admin/setBotomirAdminRole.js
> +    if (!lookupRoleName(message.guild, args.join())) {
add this line before this and use the variable instead

```
const roleName = args.join(' ');
```

2021-05-12 23:38 UTC, MarshallAsch commented on bot/commands/admin/setBotomirAdminRole.js
> +        .then(() => sendMessage(message.channel, `The admin role has been updated to ${args.join()}`))
same here

2021-05-12 23:38 UTC, MarshallAsch commented on bot/commands/admin/setBotomirAdminRole.js
> +    return config.setAdminRole(args.join())
same here

2021-05-12 23:47 UTC, MarshallAsch requested changes

2021-05-12 23:47 UTC, MarshallAsch commented on bot/commands/admin/setBotomirAdminRole.js
> +    if (!lookupRoleName(message.guild, args.join(' '))) {
I maintain my previous comment about pulling this into a variable

2021-05-13 03:38 UTC, MarshallAsch approved these changes

2021-05-15 16:42 UTC, merged